# Generated by Django 4.2.19 on 2025-03-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('prenom', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('rue', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('hebergement', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255, null=True)),
                ('identifiant_famille', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pfc.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=255, null=True)),
                ('couleur', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle'), ('U', 'Inconnu')], default='U', max_length=2)),
                ('description', models.CharField(max_length=255, null=True)),
                ('statut', models.CharField(choices=[('S', 'En refuge'), ('F', 'Accueilli'), ('A', 'Adopté')], default='S', max_length=2)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc.espece')),
                ('images_animal', models.ManyToManyField(to='pfc.media')),
                ('tags', models.ManyToManyField(to='pfc.tag')),
                ('accueillant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc.famille')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_demande', models.CharField(choices=[('Pen', 'En attente'), ('Acc', 'Validée'), ('Den', 'Refusée')], default='Pen', max_length=3)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc.animal')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc.famille')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('nom', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('rue', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('siret', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('identifiant_association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pfc.utilisateur')),
                ('images_association', models.ManyToManyField(to='pfc.media')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='potentiel_accueillant',
            field=models.ManyToManyField(related_name='potentiel_accueillant', through='pfc.Demande', to='pfc.famille'),
        ),
        migrations.AddField(
            model_name='animal',
            name='refuge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc.association'),
        ),
    ]
