# Generated by Django 4.2.19 on 2025-03-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='accueillant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pfc.famille'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='race',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='famille',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='famille',
            name='terrain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
