# Generated by Django 4.2.19 on 2025-03-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='refuge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensionnaires', to='pfc.association'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='pfc.animal'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='pfc.famille'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='accueillant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiant_famille', to='pfc.famille'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='refuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiant_association', to='pfc.association'),
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='pfc_utilisateur',
        ),
    ]
