# Generated by Django 4.2.19 on 2025-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0002_alter_animal_refuge_alter_demande_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(null=True, upload_to='images/animaux'),
        ),
    ]
