# Generated by Django 4.2.19 on 2025-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0002_alter_animal_accueillant_alter_animal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='pfc.tag'),
        ),
    ]
