# Generated by Django 4.2.19 on 2025-03-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0004_alter_animal_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='images_animal',
        ),
        migrations.RemoveField(
            model_name='association',
            name='images_association',
        ),
        migrations.AddField(
            model_name='media',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_animal', to='pfc.animal'),
        ),
        migrations.AddField(
            model_name='media',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_association', to='pfc.association'),
        ),
    ]
